export const PATH = {
    main: '/',
    login: '/login',
    register: '/register',
    forgotpassword: '/forgot-password',
    cart: '/cart',
    about: '/about',
    new_book: '/new_book',
    bestseller_book: "/bestseller_book",
    popular_book: "/popular_book",
    category_book: "/category_book",
    publisher_book: "/publisher_book",
    author_book: "/author_book",
    detail_book: "/detail_book",
    novel_book: "/novel_book",
    economic_book: "/economic_book",
    short_story_prose_book: "/short_story_prose_book",
    kid_book: "/kid_book",
    mentality_lifeskill_book: "/mentality_lifeskill_book",
    text_reference_book: "/text_reference_book",
    biography_memoir_book: "/biography_memoir_book",
    foreign_book: "/foreign_book",
    admin: {
        dashboard: "/admin",
        product_management: "/admin/product_management",
    },
    notfound: '*'
}
