function Transport() {
    return (
        <div className="flex flex-row">
            <div className="flex flex-wrap w-full bg-gray-100 py-5">
                <div className="flex flex-col w-full p-4 bg-white mx-4">
                    <span className="w-full text-2xl md:text-4xl text-center font-medium">CHÍNH SÁCH VẬN CHUYỂN/ĐÓNG GÓI</span>
                    <span className="font-medium text-center py-2">Áp dụng cho toàn bộ đơn hàng của Quý Khách tại <strong className="text-slate-700">Book Store</strong></span>

                    <span className="w-full text-lg font-medium py-3">1. Chính sách vận chuyển :</span>
                    <p className="md:text-lg"><strong className="text-slate-700">Book Store</strong> cung cấp dịch vụ giao hàng toàn quốc, gửi hàng tận nơi đến địa chỉ cung cấp của Quý khách. Thời gian giao hàng dự kiến phụ thuộc vào kho có hàng và địa chỉ nhận hàng của Quý khách.</p>
                    <p className="md:text-lg"> Với đa phần đơn hàng,<strong className="text-slate-700">Book Store</strong> cần vài giờ làm việc để kiểm tra thông tin và đóng gói hàng. Nếu các sản phẩm đều có sẵn hàng, <strong className="text-slate-700">Book Store</strong> sẽ nhanh chóng bàn giao cho đối tác vận chuyển. Nếu đơn hàng có sản phẩm sắp phát hành, <strong className="text-slate-700">Book Store</strong> sẽ ưu tiên giao những sản phẩm có hàng trước cho Quý khách hàng.</p>

                    <span className="w-full text-lg font-medium py-3">2. Một số lưu ý khi nhận hàng :</span>
                    <p className="md:text-lg">- Trước khi tiến hành giao hàng cho Quý khách, bưu tá của Đối tác vận chuyển sẽ liên hệ qua số điện thoại của Quý khách trước khoảng 3 đến 5 phút để xác nhận giao hàng.</p>
                    <p className="md:text-lg">- Nếu Quý khách không thể có mặt trong đợt nhận hàng thứ nhất, <strong className="text-slate-700">Book Store</strong> sẽ cố gắng liên lạc lại thêm ít nhất 2 lần nữa (trong 02 ca giao hàng khác nhau) để sắp xếp thời gian giao hàng, Quý khách vui lòng để ý điện thoại để liên hệ được với bưu tá giao hàng.</p>
                    <p className="md:text-lg">- Nếu qua 3 lần liên hệ giao hàng, <strong className="text-slate-700">Book Store</strong> vẫn không thể liên lạc được với Quý khách để giao hàng, <strong className="text-slate-700">Book Store</strong> sẽ thông báo cho Quý khách về việc hủy đơn hàng. Trong trường hợp Quý khách đã thanh toán trước cho đơn hàng, Quý khách sẽ nhận lại tiền vào tài khoản trong vòng 5 - 7 ngày làm việc, phụ thuộc vào tiến độ xử lý của ngân hàng. Số tiền Quý khách nhận lại sẽ trừ lại chi phí vận chuyển phát sinh từ việc giao hàng nhưng Quý khách không nhận hàng.</p>
                    <p className="md:text-lg">- Trong trường hợp Quý khách không đồng ý nhận hàng với xuất phát nguyên nhân từ hàng hóa của <strong className="text-slate-700">Book Store</strong> không đảm bảo, không đúng như mô tả, giao trễ so với cam kết,... Đơn hàng của Quý khách sẽ được hoàn lại cho chúng tôi và được hủy trên hệ thống <strong className="text-slate-700">Book Store</strong>. Nếu Quý khách đã thanh toán trước cho đơn hàng, Quý khách sẽ nhận lại tiền vào tài khoản trong vòng 5 - 7 ngày làm việc, phụ thuộc vào tiến độ xử lý của ngân hàng. Số tiền Quý khách nhận lại sẽ là toàn bộ số tiền đã thanh toán cho đơn hàng (bao gồm phí vận chuyển).</p>
                    <p className="md:text-lg">- Trong trường hợp đơn hàng đang giao đến Quý khách có ngoại quan bên ngoài hộp hàng hóa có dấu hiệu bị rách, móp, ướt, thủng, mất niêm phong,…Quý khách vui lòng kiểm tra kỹ chất lượng sản phẩm bên trong trước khi nhận hàng. Quý khách hoàn toàn có quyền từ chối nhận hàng và báo về cho chúng tôi qua hotline 1900636467 để được hỗ trợ giao lại đơn hàng mới hoặc hủy đơn hàng, hoàn tiền.</p>
                    <p className="md:text-lg">- Trong trường hợp Quý khách không có nhu cầu nhận hàng, Quý khách có thể báo với bên vận chuyển và/hoặc CSKH (qua Hotline 1900636467) về việc này. Đơn hàng của Quý khách sẽ được hoàn lại cho chúng tôi và được hủy trên hệ thống. Trong trường hợp Quý khách đã thanh toán trước cho đơn hàng, Quý khách sẽ nhận lại tiền vào tài khoản trong vòng 5 - 7 ngày làm việc, phụ thuộc vào tiến độ xử lý của ngân hàng. Số tiền Quý khách nhận lại sẽ trừ lại chi phí vận chuyển phát sinh từ việc giao hàng nhưng Quý khách không nhận.</p>
                    <p className="md:text-lg">- <strong className="text-slate-700">Book Store</strong> sẽ thông báo ngay đến Quý khách nếu có sự chậm chễ về thời gian giao hàng so với thời gian dự kiến ở trên. Trong phạm vi pháp luật cho phép, chúng tôi sẽ không chịu trách nhiệm cho bất cứ tổn thất nào, các khoản nợ, thiệt hại hoặc chi phí phát sinh từ việc giao hàng trễ. Trường hợp phát sinh chậm trễ trong việc giao hàng, nếu Quý khách không còn nhu cầu nhận hàng, <strong className="text-slate-700">Book Store</strong> cam kết sẽ hỗ trợ Quý khách hủy đơn hàng, nếu Quý khách đã thanh toán trước cho đơn hàng, Quý khách sẽ nhận lại tiền vào tài khoản trong vòng 5 - 7 ngày làm việc, phụ thuộc vào tiến độ xử lý của ngân hàng. Số tiền Quý khách nhận lại sẽ là toàn bộ số tiền đã thanh toán cho đơn hàng (bao gồm phí vận chuyển).</p>
                    <p className="md:text-lg">- Sản phẩm được đóng gói theo tiêu chuẩn đóng gói của <strong className="text-slate-700">Book Store</strong>, nếu Quý khách có nhu cầu đóng gói đặc biệt khác, vui lòng báo trước cho chúng tôi khi đặt hàng hàng và cho phép chúng tôi được tính thêm phí cho nhu cầu đặc biệt này.</p>
                    <p className="md:text-lg">- Mọi thông tin về việc thay đổi sản phẩm hay hủy bỏ đơn hàng, đề nghị Quý khách thông báo sớm để <strong className="text-slate-700">Book Store</strong> có thể điều chỉnh lại đơn hàng. Quý khách có thể liên hệ với chúng tôi qua số điện thoại hotline: 1900636467 hoặc qua địa chỉ email <strong>BookStoreCSKH@gmail.com</strong>.</p>
                </div>
            </div>
        </div>
    )
}

export default Transport;